// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_flows.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAgentFlow = `-- name: CreateAgentFlow :one
INSERT INTO agent_flows (id, name, config) VALUES ($1, $2, $3) RETURNING id, name, config, created_at, updated_at
`

type CreateAgentFlowParams struct {
	ID     uuid.UUID       `db:"id" json:"id"`
	Name   string          `db:"name" json:"name"`
	Config AgentFlowConfig `db:"config" json:"config"`
}

func (q *Queries) CreateAgentFlow(ctx context.Context, arg CreateAgentFlowParams) (AgentFlow, error) {
	row := q.db.QueryRow(ctx, createAgentFlow, arg.ID, arg.Name, arg.Config)
	var i AgentFlow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentFlow = `-- name: DeleteAgentFlow :exec
DELETE FROM agent_flows WHERE id = $1
`

func (q *Queries) DeleteAgentFlow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentFlow, id)
	return err
}

const getAgentFlowById = `-- name: GetAgentFlowById :one
SELECT id, name, config, created_at, updated_at FROM agent_flows WHERE id = $1
`

func (q *Queries) GetAgentFlowById(ctx context.Context, id uuid.UUID) (AgentFlow, error) {
	row := q.db.QueryRow(ctx, getAgentFlowById, id)
	var i AgentFlow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentFlows = `-- name: ListAgentFlows :many
SELECT id, name, config, created_at, updated_at FROM agent_flows ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAgentFlowsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListAgentFlows(ctx context.Context, arg ListAgentFlowsParams) ([]AgentFlow, error) {
	rows, err := q.db.Query(ctx, listAgentFlows, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentFlow{}
	for rows.Next() {
		var i AgentFlow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentFlow = `-- name: UpdateAgentFlow :one
UPDATE agent_flows SET name = $2, config = $3 where id = $1 RETURNING id, name, config, created_at, updated_at
`

type UpdateAgentFlowParams struct {
	ID     uuid.UUID       `db:"id" json:"id"`
	Name   string          `db:"name" json:"name"`
	Config AgentFlowConfig `db:"config" json:"config"`
}

func (q *Queries) UpdateAgentFlow(ctx context.Context, arg UpdateAgentFlowParams) (AgentFlow, error) {
	row := q.db.QueryRow(ctx, updateAgentFlow, arg.ID, arg.Name, arg.Config)
	var i AgentFlow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
