// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentFlow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Config    AgentFlowConfig    `db:"config" json:"config"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Description pgtype.Text        `db:"description" json:"description"`
	TurnCount   int32              `db:"turn_count" json:"turn_count"`
	AgentFlowID uuid.UUID          `db:"agent_flow_id" json:"agent_flow_id"`
	CreatedBy   uuid.UUID          `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SessionHistory struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	SessionID  uuid.UUID          `db:"session_id" json:"session_id"`
	Node       string             `db:"node" json:"node"`
	Content    MessageUnion       `db:"content" json:"content"`
	StopReason StopReason         `db:"stop_reason" json:"stop_reason"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Email     string             `db:"email" json:"email"`
	Provider  string             `db:"provider" json:"provider"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
