// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, created_by, agent_flow_id, title) VALUES ($1, $2, $3, $4) RETURNING id, title, description, turn_count, agent_flow_id, created_by, created_at, updated_at
`

type CreateSessionParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	CreatedBy   uuid.UUID `db:"created_by" json:"created_by"`
	AgentFlowID uuid.UUID `db:"agent_flow_id" json:"agent_flow_id"`
	Title       string    `db:"title" json:"title"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.CreatedBy,
		arg.AgentFlowID,
		arg.Title,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.TurnCount,
		&i.AgentFlowID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionByID, id)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, title, description, turn_count, agent_flow_id, created_by, created_at, updated_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.TurnCount,
		&i.AgentFlowID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionHistoryBySessionID = `-- name: GetSessionHistoryBySessionID :many
SELECT id, session_id, node, content, stop_reason, created_at FROM session_history WHERE session_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetSessionHistoryBySessionID(ctx context.Context, sessionID uuid.UUID) ([]SessionHistory, error) {
	rows, err := q.db.Query(ctx, getSessionHistoryBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionHistory{}
	for rows.Next() {
		var i SessionHistory
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Node,
			&i.Content,
			&i.StopReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsByUserID = `-- name: GetSessionsByUserID :many
SELECT id, title, description, turn_count, agent_flow_id, created_by, created_at, updated_at FROM sessions WHERE created_by = $1 ORDER BY created_at ASC
`

func (q *Queries) GetSessionsByUserID(ctx context.Context, createdBy uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsByUserID, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.TurnCount,
			&i.AgentFlowID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionAddChatHistory = `-- name: SessionAddChatHistory :one
INSERT INTO session_history (id, session_id, content, stop_reason, node) VALUES ($1, $2, $3, $4, $5) RETURNING id, session_id, node, content, stop_reason, created_at
`

type SessionAddChatHistoryParams struct {
	ID         uuid.UUID    `db:"id" json:"id"`
	SessionID  uuid.UUID    `db:"session_id" json:"session_id"`
	Content    MessageUnion `db:"content" json:"content"`
	StopReason StopReason   `db:"stop_reason" json:"stop_reason"`
	Node       string       `db:"node" json:"node"`
}

func (q *Queries) SessionAddChatHistory(ctx context.Context, arg SessionAddChatHistoryParams) (SessionHistory, error) {
	row := q.db.QueryRow(ctx, sessionAddChatHistory,
		arg.ID,
		arg.SessionID,
		arg.Content,
		arg.StopReason,
		arg.Node,
	)
	var i SessionHistory
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Node,
		&i.Content,
		&i.StopReason,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionName = `-- name: UpdateSessionName :exec
UPDATE sessions SET title = $2 WHERE id = $1
`

type UpdateSessionNameParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Title string    `db:"title" json:"title"`
}

func (q *Queries) UpdateSessionName(ctx context.Context, arg UpdateSessionNameParams) error {
	_, err := q.db.Exec(ctx, updateSessionName, arg.ID, arg.Title)
	return err
}

const updateSessionTurnCount = `-- name: UpdateSessionTurnCount :exec
UPDATE sessions SET turn_count = $2 WHERE id = $1
`

type UpdateSessionTurnCountParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	TurnCount int32     `db:"turn_count" json:"turn_count"`
}

func (q *Queries) UpdateSessionTurnCount(ctx context.Context, arg UpdateSessionTurnCountParams) error {
	_, err := q.db.Exec(ctx, updateSessionTurnCount, arg.ID, arg.TurnCount)
	return err
}
